---
title: "Modern Banking and Financial Technology"
---

This website accompanies the course of [Modern Banking and Financial Technology (B-KUL-HMA68A)](https://onderwijsaanbod.kuleuven.be/2025/syllabi/e/HMA68AE.htm).

## News & Announcements
- **14/11/2025**
	- Material and recording for **Lecture 08** is available

---

- **10/11/2025**
	- Material for **Lecture 07** is available

---

- **03/11/2025**
	- Material for **Lecture 06** is available
    - Announcement for the **Assignment** is available [here](assignment.qmd)

---

- **20/10/2025**
	- Material and recording for **Lecture 05** is available

---

- **17/10/2025**
	- Material and recording for **Lecture 04** is available

---

- **10/10/2025**
	- Material and recording for **Lecture 03** is available
    - **New**: [`All Day TA`](https://app.alldayta.com/katholieke-universiteit-leuven/mbft) is available for the course.
        - `All Day TA` is an **interactive AI tutor** trained on the course material and synced with the course schedule for learning support.

---

- **03/10/2025**
	- Material for **Lecture 02** is available
    - Recordings available for 
        - Last part of **Lecture 01** (credit card, payment model and information
        - **Lecture 02**

---

- **25/09/2025**
	- The course is live
	- Material for **Lecture 01** is available
